const DIR="daily_options_trade_klines",RAW=`https://raw.githubusercontent.com/optiona286/screenshot-system-mobile/main/${DIR}`,API=`https://api.github.com/repos/optiona286/screenshot-system-mobile/contents/${DIR}`;
const S={manifest:[],rows:[],contracts:[],expiry:"",symbol:"",bars:[],source:"1h",start:0,visible:60,hover:-1,drag:false,dragX:0,pinch:0,ind:{ma7:true,ma20:false,bb:false,highLow:true,volume:true}};
const $=x=>document.getElementById(x),U={date:$("dateSelect"),expiry:$("expirySelect"),interval:$("intervalSelect"),period:$("periodSelect"),search:$("strikeSearch"),chain:$("chainBody"),chart:$("chart"),wrap:$("chartWrap"),tip:$("chartTip"),status:$("status"),updated:$("updatedAt")},C=U.chart.getContext("2d");
const fmt=(n,d=2)=>Number.isFinite(+n)?Number(n).toLocaleString("zh-TW",{maximumFractionDigits:d}):"--",esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function toast(s){let e=$("toast");e.textContent=s;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}function status(s,ok=false){U.status.textContent=s;U.status.classList.toggle("ok",ok)}
function csv(t){let z=[],r=[],f="",q=false;for(let i=0;i<t.length;i++){let c=t[i];if(q){if(c=='"'&&t[i+1]=='"'){f+='"';i++}else if(c=='"')q=false;else f+=c}else if(c=='"')q=true;else if(c==","){r.push(f);f=""}else if(c=="\n"){r.push(f.replace(/\r$/,""));if(r.some(Boolean))z.push(r);r=[];f=""}else f+=c}if(f||r.length){r.push(f);z.push(r)}let h=(z.shift()||[]).map(x=>x.replace(/^\uFEFF/,""));return z.map(v=>Object.fromEntries(h.map((k,i)=>[k,v[i]??""])))}
const mins=p=>({"15m":15,"1h":60,"4h":240}[p]||60);
function aggregate(a,p){if(p=="source"||p==S.source)return a;let m=new Map,n=mins(p);for(let b of a){let k=Math.floor(b.time/(n*6e4))*n*6e4;if(!m.has(k))m.set(k,{...b,time:k,volume:0,trades:0,quoteVolume:0});let g=m.get(k);g.high=Math.max(g.high,b.high);g.low=Math.min(g.low,b.low);g.close=b.close;g.volume+=b.volume;g.trades+=b.trades;g.quoteVolume+=b.quoteVolume}return[...m.values()]}
async function manifest(){let r=await fetch(API,{cache:"no-store",headers:{Accept:"application/vnd.github+json"}});if(!r.ok)throw Error("找不到 GitHub 歷史資料");let re=/_(15m|1h)_(\d{4}-\d{2}-\d{2})_all_klines\.csv$/i;S.manifest=(await r.json()).map(x=>{let m=x.name.match(re);return m?{file:x.name,interval:m[1].toLowerCase(),date:m[2],size:x.size}:null}).filter(Boolean);let d=[...new Set(S.manifest.map(x=>x.date))].sort().reverse();U.date.innerHTML=d.map(x=>`<option>${x}</option>`).join("");U.date.value=d[0]||"";intervals();await dataset()}
function intervals(){let a=S.manifest.filter(x=>x.date==U.date.value).map(x=>x.interval);[...U.interval.options].forEach(o=>o.disabled=!a.includes(o.value));if(!a.includes(U.interval.value))U.interval.value=a[0]||"1h"}
async function dataset(){let x=S.manifest.find(x=>x.date==U.date.value&&x.interval==U.interval.value);if(!x)return;status(`下載 ${fmt(x.size/1048576,1)} MB`);$("spotPrice").textContent=x.date;S.source=x.interval;let r=await fetch(`${RAW}/${encodeURIComponent(x.file)}`);if(!r.ok)throw Error(`歷史檔下載失敗 ${r.status}`);status("解析歷史資料");S.rows=csv(await r.text());contracts();status(`${S.rows.length.toLocaleString()} 筆`,true);U.updated.textContent=`${x.interval} · ${fmt(x.size/1048576,1)} MB`}
function contracts(){let m=new Map;for(let r of S.rows){if(!r.symbol||![r.open,r.high,r.low,r.close].every(v=>v!==""&&Number.isFinite(+v)))continue;let side=(r.side||"").toUpperCase();if(!m.has(r.symbol))m.set(r.symbol,{symbol:r.symbol,expiry:r.expiryDate,strike:+r.strikePrice,side,open:+r.open,close:+r.close,volume:0,count:0});let x=m.get(r.symbol);x.close=+r.close;x.volume+=+(r.volume||0);x.count++}S.contracts=[...m.values()];let e=[...new Set(S.contracts.map(x=>x.expiry).filter(Boolean))].sort();U.expiry.innerHTML=e.map(x=>`<option>${esc(x)}</option>`).join("");if(!e.includes(S.expiry))S.expiry=e[0]||"";U.expiry.value=S.expiry;chain(true)}
function cell(x,type){if(!x)return'<td class="empty">—</td>';let p=x.open?(x.close/x.open-1)*100:0;return`<td><button class="quote ${type} ${x.symbol==S.symbol?"active":""}" data-symbol="${esc(x.symbol)}"><strong>${fmt(x.close,3)}</strong><small class="${p>=0?"up":"down"}">${p>=0?"+":""}${fmt(p)}% · 量 ${fmt(x.volume,1)} · ${x.count} 根</small></button></td>`}
function chain(auto=false){let q=U.search.value.trim().toLowerCase(),a=S.contracts.filter(x=>x.expiry==S.expiry&&(!q||(""+x.strike).includes(q)||x.symbol.toLowerCase().includes(q))),m=new Map;for(let x of a){if(!m.has(x.strike))m.set(x.strike,{});m.get(x.strike)[x.side.startsWith("C")?"call":"put"]=x}let ks=[...m.keys()].sort((a,b)=>a-b);$("chainCount").textContent=`${ks.length} 個履約價`;U.chain.innerHTML=ks.length?ks.map(k=>{let p=m.get(k);return`<tr>${cell(p.call,"call")}<td class="strike">${fmt(k,0)}</td>${cell(p.put,"put")}</tr>`}).join(""):'<tr><td colspan="3" class="empty">找不到符合的歷史合約</td></tr>';if(ks.length&&(auto||!a.some(x=>x.symbol==S.symbol))){let p=m.get(ks[Math.floor(ks.length/2)]);select((p.call||p.put).symbol,false)}}
function select(sym,render=true){S.symbol=sym;if(render)chain();$("symbolLabel").textContent=sym;let a=S.rows.filter(r=>r.symbol==sym).map(r=>({time:Date.parse((r.openTimeUtc||"").replace(" ","T")+"Z"),open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:+r.volume,trades:+r.numberOfTrades||0,quoteVolume:+r.quoteVolume||0})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time);S.bars=aggregate(a,U.period.value);S.visible=Math.min(60,S.bars.length);S.start=Math.max(0,S.bars.length-S.visible);S.hover=-1;quote(S.bars.at(-1));resize()}
function quote(b){if(!b)return;let f=S.bars[0],p=f?(b.close/f.open-1)*100:0;$("lastPrice").textContent=fmt(b.close,3);$("changePct").textContent=`${p>=0?"+":""}${fmt(p)}%`;$("changePct").className=p>=0?"positive":"negative";[["openValue","open"],["highValue","high"],["lowValue","low"],["closeValue","close"],["volumeValue","volume"],["tradesValue","trades"]].forEach(([id,k])=>$(id).textContent=fmt(b[k],k=="trades"?0:3))}
const ma=(a,n)=>a.map((_,i)=>i<n-1?NaN:a.slice(i-n+1,i+1).reduce((s,r)=>s+r.close,0)/n),boll=(a,n=20)=>a.map((_,i)=>{if(i<n-1)return null;let v=a.slice(i-n+1,i+1).map(r=>r.close),m=v.reduce((x,y)=>x+y,0)/n,d=Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/n);return{upper:m+2*d,lower:m-2*d}});
function resize(){let r=U.wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);U.chart.width=Math.max(1,r.width*d);U.chart.height=Math.max(1,r.height*d);C.setTransform(d,0,0,d,0,0);draw()}
function draw(){let w=U.chart.clientWidth,h=U.chart.clientHeight;C.clearRect(0,0,w,h);if(!S.bars.length)return;S.visible=Math.max(1,Math.min(S.visible,S.bars.length));S.start=Math.max(0,Math.min(S.start,S.bars.length-S.visible));let end=S.start+S.visible,a=S.bars.slice(S.start,end),L=10,R=62,T=26,B=28,V=S.ind.volume?Math.min(85,h*.2):0,PB=h-B-V,PW=w-L-R,PH=PB-T,m7=ma(S.bars,7),m20=ma(S.bars,20),bb=boll(S.bars),vals=a.flatMap(r=>[r.high,r.low]);if(S.ind.ma7)vals.push(...m7.slice(S.start,end).filter(Number.isFinite));if(S.ind.ma20)vals.push(...m20.slice(S.start,end).filter(Number.isFinite));if(S.ind.bb)bb.slice(S.start,end).filter(Boolean).forEach(b=>vals.push(b.upper,b.lower));let lo=Math.min(...vals),hi=Math.max(...vals),pad=Math.max((hi-lo)*.08,hi*.005,.01);lo=Math.max(0,lo-pad);hi+=pad;let X=i=>L+(i+.5)*PW/a.length,Y=v=>T+(hi-v)/(hi-lo||1)*PH;C.strokeStyle="#1c3142";C.fillStyle="#7892a6";C.font="10px Segoe UI";C.textAlign="left";for(let i=0;i<=5;i++){let y=T+PH*i/5;C.beginPath();C.moveTo(L,y);C.lineTo(w-R,y);C.stroke();C.fillText(fmt(hi-(hi-lo)*i/5),w-R+5,y+3)}let every=Math.max(1,Math.ceil(a.length/6));a.forEach((r,i)=>{if(i%every)return;C.textAlign="center";C.fillText(new Date(r.time).toLocaleString("zh-TW",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}),X(i),h-8)});let step=PW/a.length,cw=Math.max(2,Math.min(24,step*.72));a.forEach((r,i)=>{let x=X(i),c=r.close>=r.open?"#ff5c6b":"#22cc88";C.strokeStyle=C.fillStyle=c;C.beginPath();C.moveTo(x,Y(r.high));C.lineTo(x,Y(r.low));C.stroke();C.fillRect(x-cw/2,Math.min(Y(r.open),Y(r.close)),cw,Math.max(1,Math.abs(Y(r.open)-Y(r.close))))});function line(v,c){C.strokeStyle=c;C.beginPath();let s=false;v.forEach((n,i)=>{if(!Number.isFinite(n)){s=false;return}s?C.lineTo(X(i),Y(n)):C.moveTo(X(i),Y(n));s=true});C.stroke()}if(S.ind.ma7)line(m7.slice(S.start,end),"#ffc857");if(S.ind.ma20)line(m20.slice(S.start,end),"#37d6ff");if(S.ind.bb){line(bb.slice(S.start,end).map(x=>x?.upper),"#a889ff");line(bb.slice(S.start,end).map(x=>x?.lower),"#a889ff")}if(S.ind.highLow){let mx=a.reduce((m,r,i)=>r.high>a[m].high?i:m,0),mn=a.reduce((m,r,i)=>r.low<a[m].low?i:m,0);C.font="bold 10px Segoe UI";C.textAlign="center";C.fillStyle="#ff7884";C.fillText(`高 ${fmt(a[mx].high)}`,X(mx),Math.max(T+10,Y(a[mx].high)-7));C.fillStyle="#4ce0a6";C.fillText(`低 ${fmt(a[mn].low)}`,X(mn),Math.min(PB-3,Y(a[mn].low)+13))}if(V){let mv=Math.max(1,...a.map(r=>r.volume));a.forEach((r,i)=>{let bh=r.volume/mv*(V-18);C.fillStyle=r.close>=r.open?"#ff5c6b88":"#22cc8888";C.fillRect(X(i)-cw/2,h-B-bh,cw,bh)})}if(S.hover>=S.start&&S.hover<end){let r=S.bars[S.hover],x=X(S.hover-S.start);C.strokeStyle="#9ab0bf";C.setLineDash([4,4]);C.beginPath();C.moveTo(x,T);C.lineTo(x,h-B);C.stroke();C.beginPath();C.moveTo(L,Y(r.close));C.lineTo(w-R,Y(r.close));C.stroke();C.setLineDash([])}}
function tip(px,py){let i=Math.floor((px-10)/(U.chart.clientWidth-72)*S.visible);if(i<0||i>=S.visible)return;S.hover=S.start+i;let r=S.bars[S.hover];quote(r);U.tip.innerHTML=`<div class="tip-title"><span>${new Date(r.time).toLocaleString("zh-TW",{hour12:false})}</span><span>${U.period.value.toUpperCase()}</span></div><div class="tip-grid"><span>開 <b>${fmt(r.open)}</b></span><span>高 <b class="up">${fmt(r.high)}</b></span><span>低 <b class="down">${fmt(r.low)}</b></span><span>收 <b>${fmt(r.close)}</b></span><span>量 <b>${fmt(r.volume)}</b></span><span>筆 <b>${fmt(r.trades,0)}</b></span></div>`;U.tip.style.display="block";U.tip.style.left=Math.max(5,Math.min(U.chart.clientWidth-185,px+10))+"px";U.tip.style.top=Math.max(5,Math.min(U.chart.clientHeight-105,py+10))+"px";draw()}
function zoom(d,x){let o=S.visible,n=Math.max(Math.min(12,S.bars.length),Math.min(S.bars.length,o+d)),r=Math.max(0,Math.min(1,(x-10)/(U.chart.clientWidth-72))),anchor=S.start+Math.round(o*r);S.visible=n;S.start=Math.max(0,Math.min(S.bars.length-n,anchor-Math.round(n*r)));draw()}
U.chain.onclick=e=>{let b=e.target.closest("[data-symbol]");if(b)select(b.dataset.symbol)};U.date.onchange=()=>{intervals();dataset().catch(fail)};U.interval.onchange=()=>dataset().catch(fail);U.expiry.onchange=()=>{S.expiry=U.expiry.value;chain(true)};U.period.onchange=()=>S.symbol&&select(S.symbol);U.search.oninput=()=>chain();$("refreshBtn").onclick=()=>dataset().catch(fail);
$("chartTools").onclick=e=>{let b=e.target.closest(".toggle");if(!b)return;if(b.dataset.indicator){let k=b.dataset.indicator;S.ind[k]=!S.ind[k];b.classList.toggle("active",S.ind[k]);draw()}else if(b.dataset.action=="fit"){S.visible=S.bars.length;S.start=0;draw()}else{let a=document.createElement("a");a.download=`${S.symbol}-kline.png`;a.href=U.chart.toDataURL();a.click()}};
U.chart.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?8:-8,e.offsetX)};U.chart.onmousedown=e=>{S.drag=true;S.dragX=e.clientX};addEventListener("mouseup",()=>S.drag=false);U.chart.onmousemove=e=>{if(S.drag){let step=(U.chart.clientWidth-72)/S.visible,d=Math.round((S.dragX-e.clientX)/Math.max(step,1));if(d){S.start=Math.max(0,Math.min(S.bars.length-S.visible,S.start+d));S.dragX=e.clientX;draw()}}else tip(e.offsetX,e.offsetY)};U.chart.onmouseleave=()=>{S.drag=false;S.hover=-1;U.tip.style.display="none";quote(S.bars.at(-1));draw()};
U.chart.ontouchstart=e=>{if(e.touches.length==2)S.pinch=Math.abs(e.touches[0].clientX-e.touches[1].clientX);else{S.drag=true;S.dragX=e.touches[0].clientX;let r=U.chart.getBoundingClientRect();tip(S.dragX-r.left,e.touches[0].clientY-r.top)}};U.chart.ontouchmove=e=>{e.preventDefault();let r=U.chart.getBoundingClientRect();if(e.touches.length==2){let d=Math.abs(e.touches[0].clientX-e.touches[1].clientX);if(Math.abs(d-S.pinch)>12){zoom(d>S.pinch?-6:6,(e.touches[0].clientX+e.touches[1].clientX)/2-r.left);S.pinch=d}}else{let x=e.touches[0].clientX,step=(U.chart.clientWidth-72)/S.visible,d=Math.round((S.dragX-x)/Math.max(step,1));if(d){S.start=Math.max(0,Math.min(S.bars.length-S.visible,S.start+d));S.dragX=x;draw()}}};U.chart.ontouchend=()=>{S.drag=false;S.pinch=0};addEventListener("resize",resize);
$("captureBtn").onclick=async()=>{try{let c=await html2canvas($("captureArea"),{backgroundColor:"#071018",scale:2}),a=document.createElement("a");a.download=`BTC-History-${U.date.value}-${S.symbol}.png`;a.href=c.toDataURL();a.click();toast("完整報價畫面已下載")}catch{toast("請使用手機系統截圖")}};function fail(e){status("載入失敗");toast(e.message||"資料載入失敗")}manifest().catch(fail);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
