const DATA_DIR = "daily_options_trade_klines";
const RAW_ROOT = `https://raw.githubusercontent.com/optiona286/screenshot-system-mobile/main/${DATA_DIR}`;
const CONTENTS_API = `https://api.github.com/repos/optiona286/screenshot-system-mobile/contents/${DATA_DIR}`;
const state = { manifest: [], rows: [], contracts: [], filtered: [], side: "C", expiry: "", symbol: "", bars: [], sourceInterval: "1h" };
const $ = id => document.getElementById(id);
const ui = { date: $("dateSelect"), expiry: $("expirySelect"), interval: $("intervalSelect"), period: $("periodSelect"), search: $("strikeSearch"), list: $("contractList"), chart: $("chart"), status: $("status"), updated: $("updatedAt") };
const fmt = (n,d=2) => Number.isFinite(+n) ? Number(n).toLocaleString("zh-TW",{maximumFractionDigits:d}) : "--";
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function setStatus(text,ok=false){ui.status.textContent=text;ui.status.classList.toggle("ok",ok)}

function parseCsv(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=""}else if(c==='\n'){row.push(field.replace(/\r$/, ""));if(row.some(Boolean))rows.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const head=(rows.shift()||[]).map(x=>x.replace(/^\uFEFF/,""));return rows.map(values=>Object.fromEntries(head.map((key,i)=>[key,values[i]??""])))}
function periodMinutes(p){return {"15m":15,"1h":60,"4h":240}[p]||60}
function aggregate(items,period){if(period==="source"||period===state.sourceInterval)return items;const target=periodMinutes(period),groups=new Map();for(const b of items){const t=new Date(b.time);const bucket=Math.floor(t.getTime()/(target*60000))*target*60000;if(!groups.has(bucket))groups.set(bucket,{...b,time:bucket,volume:0});const g=groups.get(bucket);g.high=Math.max(g.high,b.high);g.low=Math.min(g.low,b.low);g.close=b.close;g.volume+=b.volume}return [...groups.values()]}

async function loadManifest(){const res=await fetch(CONTENTS_API,{cache:"no-store",headers:{Accept:"application/vnd.github+json"}});if(!res.ok)throw new Error("找不到 GitHub 歷史資料");const files=await res.json();const pattern=/_(15m|1h)_(\d{4}-\d{2}-\d{2})_all_klines\.csv$/i;state.manifest=files.map(x=>{const m=x.name.match(pattern);return m?{file:x.name,interval:m[1].toLowerCase(),date:m[2],size:x.size}:null}).filter(Boolean);const dates=[...new Set(state.manifest.map(x=>x.date))].sort().reverse();ui.date.innerHTML=dates.map(x=>`<option>${x}</option>`).join("");ui.date.value=dates[0]||"";syncIntervals();await loadDataset()}
function syncIntervals(){const available=state.manifest.filter(x=>x.date===ui.date.value).map(x=>x.interval);[...ui.interval.options].forEach(o=>o.disabled=!available.includes(o.value));if(!available.includes(ui.interval.value))ui.interval.value=available[0]||"1h"}
async function loadDataset(){const item=state.manifest.find(x=>x.date===ui.date.value&&x.interval===ui.interval.value);if(!item)return;setStatus(`下載 ${fmt(item.size/1048576,1)} MB`);$("spotPrice").textContent=item.date;state.sourceInterval=item.interval;const res=await fetch(`${RAW_ROOT}/${encodeURIComponent(item.file)}`);if(!res.ok)throw new Error(`歷史檔下載失敗 ${res.status}`);setStatus("解析歷史資料");state.rows=parseCsv(await res.text());buildContracts();setStatus(`${state.rows.length.toLocaleString()} 筆`,true);ui.updated.textContent=`${item.interval} · ${fmt(item.size/1048576,1)} MB`}
function buildContracts(){const map=new Map();for(const r of state.rows){if(!r.symbol)continue;if(!map.has(r.symbol))map.set(r.symbol,{symbol:r.symbol,expiry:r.expiryDate,strike:+r.strikePrice,side:r.side,open:+r.open,close:+r.close,count:0});const x=map.get(r.symbol);x.close=+r.close;x.count++}state.contracts=[...map.values()];const expiries=[...new Set(state.contracts.map(x=>x.expiry))].sort();ui.expiry.innerHTML=expiries.map(x=>`<option>${x}</option>`).join("");state.expiry=expiries[0]||"";renderContracts(true)}
function renderContracts(auto=false){const q=ui.search.value.trim();state.filtered=state.contracts.filter(x=>x.expiry===state.expiry&&x.side===(state.side==="C"?"CALL":"PUT")&&(!q||String(x.strike).includes(q))).sort((a,b)=>a.strike-b.strike);if(!state.filtered.length){ui.list.innerHTML='<div class="empty">找不到符合的歷史合約</div>';return}ui.list.innerHTML=state.filtered.map(x=>{const ch=x.open?(x.close/x.open-1)*100:0;return `<button class="contract ${x.symbol===state.symbol?"active":""}" data-symbol="${x.symbol}"><b>${fmt(x.strike,0)}</b><small class="${ch>=0?"positive":"negative"}">${ch>=0?"+":""}${fmt(ch)}% · ${x.count} 根</small></button>`}).join("");ui.list.querySelectorAll("button").forEach(b=>b.onclick=()=>selectContract(b.dataset.symbol));if(auto||!state.filtered.some(x=>x.symbol===state.symbol))selectContract(state.filtered[Math.floor(state.filtered.length/2)].symbol)}
function selectContract(symbol){state.symbol=symbol;renderContracts(false);$("symbolLabel").textContent=symbol;const raw=state.rows.filter(r=>r.symbol===symbol).map(r=>({time:Date.parse((r.openTimeUtc||"").replace(" ","T")+"Z"),open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:+r.volume})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time);state.bars=aggregate(raw,ui.period.value);const first=state.bars[0],last=state.bars.at(-1),ch=first?(last.close/first.open-1)*100:0;$("lastPrice").textContent=fmt(last?.close,3);$("changePct").textContent=`${ch>=0?"+":""}${fmt(ch)}%`;$("changePct").className=ch>=0?"positive":"negative";[["openValue","open"],["highValue","high"],["lowValue","low"],["closeValue","close"]].forEach(([id,k])=>$(id).textContent=fmt(last?.[k],3));drawChart()}
function drawChart(){const c=ui.chart,r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;const x=c.getContext("2d");x.scale(d,d);const w=r.width,h=r.height,p={l:12,r:54,t:15,b:25};x.clearRect(0,0,w,h);if(!state.bars.length)return;const bars=state.bars,lo=Math.min(...bars.map(b=>b.low)),hi=Math.max(...bars.map(b=>b.high)),range=hi-lo||1,y=v=>p.t+(hi-v)/range*(h-p.t-p.b),step=(w-p.l-p.r)/bars.length,body=Math.max(2,Math.min(7,step*.62));x.strokeStyle="#172b3b";x.fillStyle="#7891a4";x.font="10px Segoe UI";for(let i=0;i<5;i++){const yy=p.t+(h-p.t-p.b)*i/4;x.beginPath();x.moveTo(p.l,yy);x.lineTo(w-p.r,yy);x.stroke();x.fillText(fmt(hi-range*i/4,2),w-p.r+6,yy+3)}bars.forEach((b,i)=>{const xx=p.l+step*(i+.5);x.strokeStyle=x.fillStyle=b.close>=b.open?"#ff5f6d":"#24d18b";x.beginPath();x.moveTo(xx,y(b.high));x.lineTo(xx,y(b.low));x.stroke();x.fillRect(xx-body/2,Math.min(y(b.open),y(b.close)),body,Math.max(1,Math.abs(y(b.close)-y(b.open))))})}
document.querySelectorAll("[data-side]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-side]").forEach(x=>x.classList.toggle("active",x===b));state.side=b.dataset.side;renderContracts(true)});ui.date.onchange=()=>{syncIntervals();loadDataset().catch(e=>toast(e.message))};ui.interval.onchange=()=>loadDataset().catch(e=>toast(e.message));ui.expiry.onchange=()=>{state.expiry=ui.expiry.value;renderContracts(true)};ui.period.onchange=()=>state.symbol&&selectContract(state.symbol);ui.search.oninput=()=>renderContracts(false);$("refreshBtn").onclick=()=>loadDataset().catch(e=>toast(e.message));addEventListener("resize",drawChart);
$("captureBtn").onclick=async()=>{try{const c=await html2canvas($("captureArea"),{backgroundColor:"#071018",scale:2});const a=document.createElement("a");a.download=`BTC-History-${ui.date.value}-${state.symbol||"chart"}.png`;a.href=c.toDataURL();a.click();toast("截圖已下載")}catch{toast("請使用手機系統截圖")}};
loadManifest().catch(e=>{setStatus("載入失敗");toast(e.message)});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
